In [19]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# 훈련 데이터
x_data1 = np.array([1,2,3,4,5]).reshape(5,1)
t_data1 = np.array([3,5,7,9,11]).reshape(5,1)
print(x_data1)
print(t_data1)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [21]:
w=np.random.rand(1,1)
b=np.random.rand(1)
print(w,b)

[[0.26895645]] [0.85631412]


In [22]:
def loss_func1(x,t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/(len(x))

In [23]:
# 미분함수
def numerical_derivative1(f, x):
    delta_x=1e-4
    grad=np.zeros_like(x)

    it = np.nditer(x,flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index

        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x) # f(x+delta_x)

        x[idx]=float(tmp_val)-delta_x
        fx2=f(x) # f(x+delta_x)

        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()

    return grad

In [24]:
# 예측함수
def predict1(x):
    y=np.dot(x,w)+b
    return y

In [25]:
# 학습
cost_list=[]
learning_rate=1e-2

f=lambda x: loss_func1(x_data1, t_data1)

print("Initial error value=", loss_func1(x_data1, t_data1), "Initial w=", w, "b=", b)

for step in range(201):
    w-=learning_rate*numerical_derivative1(f,w)
    b-=learning_rate*numerical_derivative1(f,b)
    cost_list.append([step, loss_func1(x_data1, t_data1)])

    if step % 100 == 0:
        print("step=", step, "error value=",
              loss_func1(x_data1, t_data1), "w=", w, "b=", b)

Initial error value= 34.47463433063307 Initial w= [[0.26895645]] b= [0.85631412]
step= 0 error value= 20.28774413711751 w= [[0.65840718]] b= [0.93968341]
step= 100 error value= 0.004293282130377835 w= [[1.9574508]] b= [1.15357853]
step= 200 error value= 0.0021577675565372678 w= [[1.9698353]] b= [1.1088775]


In [27]:
result1=predict1(np.array([7]))
result2=predict1(np.array([[7],[8]]))
print(result1)
print(result2)

[14.89772457]
[[14.89772457]
 [16.86755987]]


In [28]:
x_data1 = [
    [73., 80., 75.],
    [93., 88., 93.],
    [89., 91., 90.],
    [96., 98., 100.],
    [73., 66., 70.]
]
t_data1 = [
    [152.],
    [152.],
    [152.],
    [152.],
    [152.],
]
x_data = np.array(x_data1)
t_data = np.array(t_data1)
print(x_data)
print(t_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [152.]
 [152.]
 [152.]
 [152.]]


In [29]:
# weight, bais
w=np.random.rand(3,1)
b=np.random.rand(1)
print(w,b)

[[0.65564138]
 [0.95431279]
 [0.79855735]] [0.12562268]


In [ ]:
learning_rate=1e-6

f=lambda x: loss_func1(x_data, t_data)

print("Initial error value=", loss_func1(x_data, t_data), "Initial w=", w, "b=", b)

for step in range(20001):
    w-=learning_rate*numerical_derivative1(f,w)
    b-=learning_rate*numerical_derivative1(f,b)

    if step % 400 == 0:
        print("step=", step, "error value=",
              loss_func1(x_data, t_data), "w=", w, "b=", b)

Initial error value= 3435.164503414696 Initial w= [[0.65564138]
 [0.95431279]
 [0.79855735]] b= [0.12562268]
step= 0 error value= 3169.7049779156864 w= [[0.64619745]
 [0.94483525]
 [0.78894429]] b= [0.1255219]
step= 400 error value= 350.922932867344 w= [[0.45392106]
 [0.73561843]
 [0.57074629]] b= [0.12506872]
step= 800 error value= 350.1802202609755 w= [[0.46743801]
 [0.73213687]
 [0.56080175]] b= [0.12690239]
step= 1200 error value= 349.4433214705352 w= [[0.48088467]
 [0.7287305 ]
 [0.55085246]] b= [0.12873423]
step= 1600 error value= 348.7121314202876 w= [[0.49426172]
 [0.72539847]
 [0.54089859]] b= [0.13056427]
step= 2000 error value= 347.98654724970083 w= [[0.50756985]
 [0.72213994]
 [0.53094029]] b= [0.1323925]
step= 2400 error value= 347.2664682660084 w= [[0.52080971]
 [0.71895409]
 [0.52097773]] b= [0.13421893]
step= 2800 error value= 346.5517958978061 w= [[0.53398197]
 [0.71584008]
 [0.51101105]] b= [0.13604356]
step= 3200 error value= 345.84243364962606 w= [[0.54708729]
 [0.7

In [31]:
result3=predict1(np.array([[70,85,75],[80,85,80]]))
print(result3)

[[133.75023605]
 [144.60051382]]
