### 1. 계정 삭제 - 터미널
conda activate base
conda remove -n test1 --all

### 2. 재설치 - 터미널
주피터와 파이썬 연결 : ipykernel
conda create -n test1 python=3.14 ipykernel -y

### 3. 주피터 셀(터미널x)에서 파이토치 설치
!pip3 install torch torchvision 

### 4. 임포트
import torch
torch.__version__

In [2]:
!pip3 install torch torchvision

In [3]:
import torch
torch.__version__

'2.10.0+cpu'

In [4]:
a=[[1,2,3,4],[10,20,30,40]]
t1=torch.tensor(a, dtype=torch.float64)
t1

tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]], dtype=torch.float64)

In [5]:
ft=torch.FloatTensor(a);
print(ft)
lt=torch.FloatTensor(a);
print(lt)
bt=torch.FloatTensor(a);
print(bt)

tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]])
tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]])
tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]])


In [6]:
import numpy as np

In [7]:
x=np.array(a)
print(x, type(x))

[[ 1  2  3  4]
 [10 20 30 40]] <class 'numpy.ndarray'>


In [8]:
tx=torch.from_numpy(x)
print(tx, type(tx))

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]]) <class 'torch.Tensor'>


In [9]:
x1=tx.numpy()
print(x1, type(x1))

[[ 1  2  3  4]
 [10 20 30 40]] <class 'numpy.ndarray'>


In [10]:
print(tx)
ft=tx.float()
print(ft)
lt=ft.byte()
print(lt)

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]])
tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]])
tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]], dtype=torch.uint8)


In [11]:
list=[[[1,2,3],[1,2,3]],[[5,6,7],[7,8,9]],[[9,10,11],[11,12,13]]]
list

[[[1, 2, 3], [1, 2, 3]], [[5, 6, 7], [7, 8, 9]], [[9, 10, 11], [11, 12, 13]]]

In [12]:
t1=torch.FloatTensor(list)
t1

tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])

In [13]:
print(t1.size())
print(t1.shape)
print(t1.size(-1))
print(t1.shape[-1])
print(t1.dim()) # 차원
print(len(t1.size()))

torch.Size([3, 2, 3])
torch.Size([3, 2, 3])
3
3
3
3


In [14]:
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,2]])
print(a,b)

tensor([[1., 2.],
        [3., 4.]]) tensor([[2., 2.],
        [3., 2.]])


In [15]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a==b)
print(a!=b)
print(a**b)
print(a)
print(b)
print(a.mul_(b))
print(a)

tensor([[3., 4.],
        [6., 6.]])
tensor([[-1.,  0.],
        [ 0.,  2.]])
tensor([[2., 4.],
        [9., 8.]])
tensor([[0.5000, 1.0000],
        [1.0000, 2.0000]])
tensor([[1., 0.],
        [0., 0.]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])
tensor([[ 1.,  4.],
        [27., 16.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [3., 2.]])
tensor([[2., 4.],
        [9., 8.]])
tensor([[2., 4.],
        [9., 8.]])


In [16]:
print(a.sum())
print(a.mean())
print(a.sum(dim=0))
print(a.sum(dim=1))
print(a.mean(dim=0))
print(a.mean(dim=1))
print(a.sum(dim=-1))

tensor(23.)
tensor(5.7500)
tensor([11., 12.])
tensor([ 6., 17.])
tensor([5.5000, 6.0000])
tensor([3.0000, 8.5000])
tensor([ 6., 17.])


In [17]:
tx

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]])

In [18]:
t1

tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])

In [19]:
t1.sum(dim=2)

tensor([[ 6.,  6.],
        [18., 24.],
        [30., 36.]])

In [20]:
print(t1+10)
print(t1-1)

tensor([[[11., 12., 13.],
         [11., 12., 13.]],

        [[15., 16., 17.],
         [17., 18., 19.]],

        [[19., 20., 21.],
         [21., 22., 23.]]])
tensor([[[ 0.,  1.,  2.],
         [ 0.,  1.,  2.]],

        [[ 4.,  5.,  6.],
         [ 6.,  7.,  8.]],

        [[ 8.,  9., 10.],
         [10., 11., 12.]]])


In [21]:
print(t1)
t0=torch.tensor([1,2,3])
print(t1+t0)

tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])
tensor([[[ 2.,  4.,  6.],
         [ 2.,  4.,  6.]],

        [[ 6.,  8., 10.],
         [ 8., 10., 12.]],

        [[10., 12., 14.],
         [12., 14., 16.]]])


In [22]:
t1
t2=torch.tensor([[1,2,3],[3,4,5]])
print(t1)
print(t2)
print(t1+t2)

tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])
tensor([[1, 2, 3],
        [3, 4, 5]])
tensor([[[ 2.,  4.,  6.],
         [ 4.,  6.,  8.]],

        [[ 6.,  8., 10.],
         [10., 12., 14.]],

        [[10., 12., 14.],
         [14., 16., 18.]]])


In [23]:
x2=torch.FloatTensor([[[1,2,8]]])
y2=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
print(x2+y2)

tensor([[[ 2.,  4., 11.],
         [ 5.,  7., 14.],
         [ 8., 10., 17.]]])


In [24]:
t1.size()
t1

tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])

In [25]:
print(t1.view(-1,3))
print(t1.view(3,-1))
print(t1.view(3,6))
print(t1.view(2,3,3))
print(t1.view(3,3,2))

tensor([[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 5.,  6.,  7.],
        [ 7.,  8.,  9.],
        [ 9., 10., 11.],
        [11., 12., 13.]])
tensor([[ 1.,  2.,  3.,  1.,  2.,  3.],
        [ 5.,  6.,  7.,  7.,  8.,  9.],
        [ 9., 10., 11., 11., 12., 13.]])
tensor([[ 1.,  2.,  3.,  1.,  2.,  3.],
        [ 5.,  6.,  7.,  7.,  8.,  9.],
        [ 9., 10., 11., 11., 12., 13.]])
tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.],
         [ 5.,  6.,  7.]],

        [[ 7.,  8.,  9.],
         [ 9., 10., 11.],
         [11., 12., 13.]]])
tensor([[[ 1.,  2.],
         [ 3.,  1.],
         [ 2.,  3.]],

        [[ 5.,  6.],
         [ 7.,  7.],
         [ 8.,  9.]],

        [[ 9., 10.],
         [11., 11.],
         [12., 13.]]])


In [27]:
print(t1.reshape(-1,3))
print(t1.reshape(3,-1))
print(t1.view(3,6))
print(t1.view(2,3,3))
print(t1.view(3,3,2))

tensor([[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 5.,  6.,  7.],
        [ 7.,  8.,  9.],
        [ 9., 10., 11.],
        [11., 12., 13.]])
tensor([[ 1.,  2.,  3.,  1.,  2.,  3.],
        [ 5.,  6.,  7.,  7.,  8.,  9.],
        [ 9., 10., 11., 11., 12., 13.]])
tensor([[ 1.,  2.,  3.,  1.,  2.,  3.],
        [ 5.,  6.,  7.,  7.,  8.,  9.],
        [ 9., 10., 11., 11., 12., 13.]])
tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.],
         [ 5.,  6.,  7.]],

        [[ 7.,  8.,  9.],
         [ 9., 10., 11.],
         [11., 12., 13.]]])
tensor([[[ 1.,  2.],
         [ 3.,  1.],
         [ 2.,  3.]],

        [[ 5.,  6.],
         [ 7.,  7.],
         [ 8.,  9.]],

        [[ 9., 10.],
         [11., 11.],
         [12., 13.]]])


In [28]:
print(t1.view(-1,3,3,2))

tensor([[[[ 1.,  2.],
          [ 3.,  1.],
          [ 2.,  3.]],

         [[ 5.,  6.],
          [ 7.,  7.],
          [ 8.,  9.]],

         [[ 9., 10.],
          [11., 11.],
          [12., 13.]]]])


In [29]:
t10=t1.view(3,2,1,3)
print(t10.size())
t11=t10.squeeze()
print(t11.size())
t12=t11.unsqueeze(1)
print(t12.size())
print(t1)
print(t10)
print(t11)

torch.Size([3, 2, 1, 3])
torch.Size([3, 2, 3])
torch.Size([3, 1, 2, 3])
tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])
tensor([[[[ 1.,  2.,  3.]],

         [[ 1.,  2.,  3.]]],


        [[[ 5.,  6.,  7.]],

         [[ 7.,  8.,  9.]]],


        [[[ 9., 10., 11.]],

         [[11., 12., 13.]]]])
tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])


In [30]:
print(t1)
print(t1[2,:,1])

tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])
tensor([10., 12.])


In [31]:
x=torch.FloatTensor(10,4)
splits=x.split(4, dim=0)
splits

(tensor([[5.8505e+14, 1.4910e-42, 0.0000e+00, 2.2500e+00],
         [0.0000e+00, 2.3750e+00, 0.0000e+00, 2.0000e+00],
         [0.0000e+00, 2.2500e+00, 0.0000e+00, 2.3750e+00],
         [0.0000e+00, 2.3750e+00, 0.0000e+00, 2.5000e+00]]),
 tensor([[0.0000, 2.5625, 0.0000, 2.5000],
         [0.0000, 2.5625, 0.0000, 2.6250],
         [0.0000, 2.5625, 0.0000, 2.6250],
         [0.0000, 2.6875, 0.0000, 2.6250]]),
 tensor([[0.0000, 2.6875, 0.0000, 2.7500],
         [0.0000, 0.0000, 0.0000, 0.0000]]))

In [32]:
chunks=x.chunk(4, dim=0)
chunks

(tensor([[5.8505e+14, 1.4910e-42, 0.0000e+00, 2.2500e+00],
         [0.0000e+00, 2.3750e+00, 0.0000e+00, 2.0000e+00],
         [0.0000e+00, 2.2500e+00, 0.0000e+00, 2.3750e+00]]),
 tensor([[0.0000, 2.3750, 0.0000, 2.5000],
         [0.0000, 2.5625, 0.0000, 2.5000],
         [0.0000, 2.5625, 0.0000, 2.6250]]),
 tensor([[0.0000, 2.5625, 0.0000, 2.6250],
         [0.0000, 2.6875, 0.0000, 2.6250],
         [0.0000, 2.6875, 0.0000, 2.7500]]),
 tensor([[0., 0., 0., 0.]]))

In [33]:
x=torch.FloatTensor(8,4)
chunks=x.chunk(3, dim=0)
print(chunks)

(tensor([[5.9379e+14, 1.4910e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]))


In [34]:
print(t1)
indice=torch.LongTensor([2,1])
y=t1.index_select(dim=0, index=indice)
print(y)

tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])
tensor([[[ 9., 10., 11.],
         [11., 12., 13.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]]])


In [35]:
x=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
y=torch.FloatTensor([[11,12,13],[14,15,16],[17,18,19]])
print(x.size())
print(y.size())

torch.Size([3, 3])
torch.Size([3, 3])


In [36]:
z=torch.cat([x,y], dim=1)
print(z)
z1=torch.stack([x,y])
z1

tensor([[ 1.,  2.,  3., 11., 12., 13.],
        [ 4.,  5.,  6., 14., 15., 16.],
        [ 7.,  8.,  9., 17., 18., 19.]])


tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[11., 12., 13.],
         [14., 15., 16.],
         [17., 18., 19.]]])

In [37]:
x=torch.FloatTensor([[[1,2]],[[3,4]]])
print(x.size())
y=x.expand(2,3,2)
print(y)

torch.Size([2, 1, 2])
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


In [38]:
y=torch.cat([x]*3, dim=1)
y

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])

In [39]:
x=torch.randperm(10)
x

tensor([8, 6, 5, 1, 4, 0, 7, 2, 3, 9])

In [40]:
x=torch.randperm(3**3).reshape(3,3,-1)
print(x)

tensor([[[17,  2, 11],
         [16, 23, 20],
         [18, 14, 26]],

        [[ 4, 25,  3],
         [ 5, 19, 22],
         [21, 13,  1]],

        [[ 6,  8, 12],
         [24, 10, 15],
         [ 9,  0,  7]]])


In [41]:
y1=x.argmax(dim=-1)
print(y1)

tensor([[0, 1, 2],
        [1, 2, 0],
        [2, 0, 0]])


In [42]:
x

tensor([[[17,  2, 11],
         [16, 23, 20],
         [18, 14, 26]],

        [[ 4, 25,  3],
         [ 5, 19, 22],
         [21, 13,  1]],

        [[ 6,  8, 12],
         [24, 10, 15],
         [ 9,  0,  7]]])

In [43]:
values, indices = torch.topk(x, k=2, dim=0)
print(values)

tensor([[[17, 25, 12],
         [24, 23, 22],
         [21, 14, 26]],

        [[ 6,  8, 11],
         [16, 19, 20],
         [18, 13,  7]]])


In [44]:
x1=torch.FloatTensor([i for i in range(3**2)]).view(3,-1)

print(x1)
mask=x1>4
print(mask)
y1=x1.masked_fill(mask, value=0)
y1
x2=torch.randperm(9).view(3,-1)
print(x2)
mask2=x2>4
mask2
y2=x2.masked_fill(mask2, value=-1)
y2

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([[2, 8, 1],
        [6, 7, 3],
        [0, 4, 5]])


tensor([[ 2, -1,  1],
        [-1, -1,  3],
        [ 0,  4, -1]])

In [45]:
print(torch.ones(2,3))
print(torch.zeros(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [46]:
x=torch.FloatTensor([[1,2,3],[4,5,6]])
x.size()

torch.Size([2, 3])

In [47]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
