### 1. 계정 삭제 - 터미널
conda activate base
conda remove -n test1 --all

### 2. 재설치 - 터미널
주피터와 파이썬 연결 : ipykernel
conda create -n test1 python=3.14 ipykernel -y

### 3. 주피터 셀(터미널x)에서 파이토치 설치
!pip3 install torch torchvision 

### 4. 임포트
import torch
torch.__version__

In [6]:
!pip3 install torch torchvision

In [7]:
import torch
torch.__version__

'2.10.0+cpu'

In [8]:
a=[[1,2,3,4],[10,20,30,40]]
t1=torch.tensor(a, dtype=torch.float64)
t1

tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]], dtype=torch.float64)

In [9]:
ft=torch.FloatTensor(a);
print(ft)
lt=torch.FloatTensor(a);
print(lt)
bt=torch.FloatTensor(a);
print(bt)

tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]])
tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]])
tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]])


In [10]:
import numpy as np

In [11]:
x=np.array(a)
print(x, type(x))

[[ 1  2  3  4]
 [10 20 30 40]] <class 'numpy.ndarray'>


In [12]:
tx=torch.from_numpy(x)
print(tx, type(tx))

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]]) <class 'torch.Tensor'>


In [13]:
x1=tx.numpy()
print(x1, type(x1))

[[ 1  2  3  4]
 [10 20 30 40]] <class 'numpy.ndarray'>


In [14]:
print(tx)
ft=tx.float()
print(ft)
lt=ft.byte()
print(lt)

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]])
tensor([[ 1.,  2.,  3.,  4.],
        [10., 20., 30., 40.]])
tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]], dtype=torch.uint8)


In [15]:
list=[[[1,2,3],[1,2,3]],[[5,6,7],[7,8,9]],[[9,10,11],[11,12,13]]]
list

[[[1, 2, 3], [1, 2, 3]], [[5, 6, 7], [7, 8, 9]], [[9, 10, 11], [11, 12, 13]]]

In [16]:
t1=torch.FloatTensor(list)
t1

tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  3.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])

In [17]:
print(t1.size())
print(t1.shape)
print(t1.size(-1))
print(t1.shape[-1])
print(t1.dim()) # 차원
print(len(t1.size()))

torch.Size([3, 2, 3])
torch.Size([3, 2, 3])
3
3
3
3


In [18]:
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,2]])
print(a,b)

tensor([[1., 2.],
        [3., 4.]]) tensor([[2., 2.],
        [3., 2.]])


In [19]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a==b)
print(a!=b)
print(a**b)
print(a)
print(b)
print(a.mul_(b))
print(a)

tensor([[3., 4.],
        [6., 6.]])
tensor([[-1.,  0.],
        [ 0.,  2.]])
tensor([[2., 4.],
        [9., 8.]])
tensor([[0.5000, 1.0000],
        [1.0000, 2.0000]])
tensor([[1., 0.],
        [0., 0.]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])
tensor([[ 1.,  4.],
        [27., 16.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [3., 2.]])
tensor([[2., 4.],
        [9., 8.]])
tensor([[2., 4.],
        [9., 8.]])


In [20]:
print(a.sum())
print(a.mean())
print(a.sum(dim=0))
print(a.sum(dim=1))
print(a.mean(dim=0))
print(a.mean(dim=1))
print(a.sum(dim=-1))

tensor(23.)
tensor(5.7500)
tensor([11., 12.])
tensor([ 6., 17.])
tensor([5.5000, 6.0000])
tensor([3.0000, 8.5000])
tensor([ 6., 17.])
