In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [2]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

### 입력 1개, 1변수, 단순회귀

In [3]:
model=nn.Linear(1,1) # input_dim=1, output_dim=1  y=wx+b
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [4]:
optimizer=optim.SGD(model.parameters(), lr=0.01)
epochs=2001

for epoch in range(epochs):
    h=model(x_data)
    cost=F.mse_loss(h,t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0:
        print('epoch:',epoch, 'cost:',cost.item())


epoch: 0 cost: 39.16685104370117
epoch: 100 cost: 0.08463062345981598
epoch: 200 cost: 0.04298952594399452
epoch: 300 cost: 0.021837208420038223
epoch: 400 cost: 0.01109258271753788
epoch: 500 cost: 0.00563468411564827
epoch: 600 cost: 0.0028622171375900507
epoch: 700 cost: 0.0014539161929860711
epoch: 800 cost: 0.0007385412463918328
epoch: 900 cost: 0.00037515218718908727
epoch: 1000 cost: 0.00019056595920119435
epoch: 1100 cost: 9.680409129941836e-05
epoch: 1200 cost: 4.91717473778408e-05
epoch: 1300 cost: 2.497919740562793e-05
epoch: 1400 cost: 1.2689983122982085e-05
epoch: 1500 cost: 6.447205578297144e-06
epoch: 1600 cost: 3.276181814726442e-06
epoch: 1700 cost: 1.6654261116855196e-06
epoch: 1800 cost: 8.460160643153358e-07
epoch: 1900 cost: 4.302897309571563e-07
epoch: 2000 cost: 2.1860606125301274e-07


In [5]:
x=torch.FloatTensor([3])
model(x)

tensor([6.9998], grad_fn=<ViewBackward0>)

### 입력 3개, 다변수, 다중회귀

In [6]:
import pandas as pd
df=pd.read_csv('test-data(score).csv')
data=np.array(df.values)
#print(data)
x_data=data[:,:3].reshape(-1, 3)
t_data=data[:,-1].reshape(-1, 1)
print(x_data)
print(t_data)
x_data3=torch.from_numpy(x_data).float()
t_data3=torch.from_numpy(t_data).float()
print(x_data3)
print(t_data3)

[[ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]
[[185]
 [180]
 [196]
 [142]
 [101]
 [149]
 [115]
 [175]
 [164]
 [141]
 [141]
 [184]
 [152]
 [148]
 [192]
 [147]
 [183]
 [177]
 [159]
 [177]
 [175]
 [175]
 [149]
 [192]]
tensor([[ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.],
        [ 53.,  46.,  55.],
        [ 69.,  74.,  77.],
        [ 47.,  56.,  60.],
        [ 87.,  79.,  90.],
        [ 79.,  70.,  88.],
        [ 69.,  70.,  73.],
        [ 70.,  65.,  74.],
        [ 93.,  95.,  91.],
        [ 79.,  80.,  73.],
        [ 70.,  73.,  78.],
        [ 93.,  89.,  96.],
        [ 78.,  75.,  68.],
        [ 81.,  90.,  

In [7]:
torch.manual_seed(1)
model=nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [8]:
optimizer=optim.SGD(model.parameters(), lr=1e-6)
epochs=20001
for epoch in range(epochs):
    y=model(x_data3)  #y=wx+b
    cost=F.mse_loss(y, t_data3)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400==0:
        print('epoch:',epoch, 'cost:',cost.item())
        print('Parameters:', list(model.parameters()))

epoch: 0 cost: 28838.4140625
Parameters: [Parameter containing:
tensor([[ 0.3247, -0.2275, -0.0839]], requires_grad=True), Parameter containing:
tensor([0.2713], requires_grad=True)]
epoch: 400 cost: 16.228923797607422
Parameters: [Parameter containing:
tensor([[0.9820, 0.4371, 0.6067]], requires_grad=True), Parameter containing:
tensor([0.2795], requires_grad=True)]
epoch: 800 cost: 15.98615550994873
Parameters: [Parameter containing:
tensor([[0.9753, 0.4362, 0.6139]], requires_grad=True), Parameter containing:
tensor([0.2795], requires_grad=True)]
epoch: 1200 cost: 15.749836921691895
Parameters: [Parameter containing:
tensor([[0.9688, 0.4354, 0.6211]], requires_grad=True), Parameter containing:
tensor([0.2795], requires_grad=True)]
epoch: 1600 cost: 15.519780158996582
Parameters: [Parameter containing:
tensor([[0.9623, 0.4347, 0.6281]], requires_grad=True), Parameter containing:
tensor([0.2795], requires_grad=True)]
epoch: 2000 cost: 15.29581069946289
Parameters: [Parameter containin

In [9]:
x=torch.FloatTensor([[75,80,85],[80,75,85],[75,85,80]])
model(x)

tensor([[162.4106],
        [163.9007],
        [160.2614]], grad_fn=<AddmmBackward0>)