## Class 로 구현

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [2]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [3]:
class LinearRegressionModel(nn.Module):
    def __init__(self): # 모델 생성
        super().__init__()
        self.linear=nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

In [4]:
model=LinearRegressionModel()
print(list(model.parameters()))
optimizer=optim.SGD(model.parameters(), lr=0.01)

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [5]:
epochs=2001
for epoch in range(epochs):
    y=model(x_data)
    cost=F.mse_loss(y, t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        print(epoch, cost.item(), list(model.parameters()))

0 39.16685104370117 [Parameter containing:
tensor([[0.9284]], requires_grad=True), Parameter containing:
tensor([-0.3235], requires_grad=True)]
100 0.08463062345981598 [Parameter containing:
tensor([[2.1882]], requires_grad=True), Parameter containing:
tensor([0.3204], requires_grad=True)]
200 0.04298952594399452 [Parameter containing:
tensor([[2.1342]], requires_grad=True), Parameter containing:
tensor([0.5157], requires_grad=True)]
300 0.021837208420038223 [Parameter containing:
tensor([[2.0956]], requires_grad=True), Parameter containing:
tensor([0.6548], requires_grad=True)]
400 0.01109258271753788 [Parameter containing:
tensor([[2.0681]], requires_grad=True), Parameter containing:
tensor([0.7540], requires_grad=True)]
500 0.00563468411564827 [Parameter containing:
tensor([[2.0486]], requires_grad=True), Parameter containing:
tensor([0.8246], requires_grad=True)]
600 0.0028622171375900507 [Parameter containing:
tensor([[2.0346]], requires_grad=True), Parameter containing:
tensor([0

In [6]:
import pandas as pd
df=pd.read_csv('test-data(score).csv')
data=np.array(df.values)
#print(data)
x_data=data[:,:3].reshape(-1, 3)
t_data=data[:,-1].reshape(-1, 1)
print(x_data)
print(t_data)
x_data3=torch.from_numpy(x_data).float()
t_data3=torch.from_numpy(t_data).float()
print(x_data3)
print(t_data3)

[[ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]
[[185]
 [180]
 [196]
 [142]
 [101]
 [149]
 [115]
 [175]
 [164]
 [141]
 [141]
 [184]
 [152]
 [148]
 [192]
 [147]
 [183]
 [177]
 [159]
 [177]
 [175]
 [175]
 [149]
 [192]]
tensor([[ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.],
        [ 53.,  46.,  55.],
        [ 69.,  74.,  77.],
        [ 47.,  56.,  60.],
        [ 87.,  79.,  90.],
        [ 79.,  70.,  88.],
        [ 69.,  70.,  73.],
        [ 70.,  65.,  74.],
        [ 93.,  95.,  91.],
        [ 79.,  80.,  73.],
        [ 70.,  73.,  78.],
        [ 93.,  89.,  96.],
        [ 78.,  75.,  68.],
        [ 81.,  90.,  

In [7]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)

In [8]:
model=MultiLinearRegressionModel()
optimizer=optim.SGD(model.parameters(), lr=1e-6)

In [9]:
epochs=200001
for epoch in range(epochs):
    y=model(x_data3)
    cost=F.mse_loss(y, t_data3)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400==0:
        print(epoch, cost.item(), list(model.parameters()))

0 38396.9765625 [Parameter containing:
tensor([[-0.0805,  0.3024, -0.5112]], requires_grad=True), Parameter containing:
tensor([0.3466], requires_grad=True)]
400 29.320838928222656 [Parameter containing:
tensor([[0.6815, 1.0598, 0.2912]], requires_grad=True), Parameter containing:
tensor([0.3561], requires_grad=True)]
800 28.53531837463379 [Parameter containing:
tensor([[0.6774, 1.0496, 0.3051]], requires_grad=True), Parameter containing:
tensor([0.3562], requires_grad=True)]
1200 27.776960372924805 [Parameter containing:
tensor([[0.6734, 1.0395, 0.3188]], requires_grad=True), Parameter containing:
tensor([0.3562], requires_grad=True)]
1600 27.044736862182617 [Parameter containing:
tensor([[0.6695, 1.0297, 0.3322]], requires_grad=True), Parameter containing:
tensor([0.3562], requires_grad=True)]
2000 26.337865829467773 [Parameter containing:
tensor([[0.6656, 1.0200, 0.3454]], requires_grad=True), Parameter containing:
tensor([0.3563], requires_grad=True)]
2400 25.655359268188477 [Param

In [10]:
x=torch.FloatTensor([[75,80,85],[80,75,85],[75,85,80]])
model(x)

tensor([[164.9772],
        [164.0319],
        [162.0736]], grad_fn=<AddmmBackward0>)