In [ ]:
# !pip install pandas

  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 9.9/9.9 MB 59.7 MB/s  0:00:00
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)

   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x_data1=np.array([[1,2],[2,3],[3,4],[4,5],[5,6]]).reshape(5,2)
t_data1=np.array([3,5,7,9,11]).reshape(5,1)
print(x_data1)
print(t_data1)

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [3]:
w=np.random.rand(2,1)
b=np.random.rand(1)
print(w)
print(b)

[[0.99296956]
 [0.92057755]]
[0.2414406]


In [4]:
def loss_func(x, t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/(len(x))

In [5]:
def numerical_derivative(f, x):
    delta_x=1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]

        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()
        
    return grad

In [6]:
def predict(x):
    y=np.dot(x, w)+b
    return y

In [7]:
learning_rate=1e-4
f=lambda x:loss_func(x_data1, t_data1)
print('초기값=', loss_func(x_data1, t_data1), '초기 가중치(w)=',w, '초기 편향(b)=',b)

for step in range(200001):
    w-=learning_rate*numerical_derivative(f, w)
    b-=learning_rate*numerical_derivative(f, b)

    if step %100==0:
        print('단계=%05d'%step, '오차값=%2.5f'%loss_func(x_data1, t_data1), '가중치=%1.5f%1.5f%',w ,'편향=',b)

초기값= 0.02442338106077091 초기 가중치(w)= [[0.99296956]
 [0.92057755]] 초기 편향(b)= [0.2414406]
단계=00000 오차값=0.02421 가중치=%1.5f%1.5f% [[0.99306255]
 [0.92069   ]] 편향= [0.24145992]
단계=00100 오차값=0.01166 가중치=%1.5f%1.5f% [[1.00013771]
 [0.92908576]] 편향= [0.24276956]
단계=00200 오차값=0.00782 가중치=%1.5f%1.5f% [[1.00420301]
 [0.93362481]] 편향= [0.24323724]
단계=00300 오차값=0.00663 가중치=%1.5f%1.5f% [[1.00661188]
 [0.93604258]] 편향= [0.24324276]
단계=00400 오차값=0.00623 가중치=%1.5f%1.5f% [[1.00810886]
 [0.93729377]] 편향= [0.24299506]
단계=00500 오차값=0.00608 가중치=%1.5f%1.5f% [[1.00910353]
 [0.93790353]] 편향= [0.24260908]
단계=00600 오차값=0.00600 가중치=%1.5f%1.5f% [[1.00982117]
 [0.93816076]] 편향= [0.24214803]
단계=00700 오차값=0.00594 가중치=%1.5f%1.5f% [[1.01038574]
 [0.93822437]] 편향= [0.24164668]
단계=00800 오차값=0.00589 가중치=%1.5f%1.5f% [[1.01086543]
 [0.9381818 ]] 편향= [0.24112416]
단계=00900 오차값=0.00584 가중치=%1.5f%1.5f% [[1.01129774]
 [0.93808111]] 편향= [0.24059099]
단계=01000 오차값=0.00580 가중치=%1.5f%1.5f% [[1.01170331]
 [0.93794878]] 편향= [0.24005295]


In [8]:
predict(np.array([[7,8]]))
# predict(np.array([[11,12]]))

array([[14.99994256]])

In [9]:
predict(np.array([[11,12]]))

array([[22.9998761]])

In [12]:
import pandas as pd
df=pd.read_csv('test-data(score).csv')
data=np.array(df.values)
x_data=data[:,:3].reshape(-1, 3)
t_data=data[:,-1].reshape(-1, 1)
print(x_data)
print(t_data)

[[ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]
[[185]
 [180]
 [196]
 [142]
 [101]
 [149]
 [115]
 [175]
 [164]
 [141]
 [141]
 [184]
 [152]
 [148]
 [192]
 [147]
 [183]
 [177]
 [159]
 [177]
 [175]
 [175]
 [149]
 [192]]


In [ ]:
w=np.random.rand(3,1)
b=np.random.rand(1)
print(w)
print(b)

[[0.94531651]
 [0.81143993]
 [0.1711562 ]]
[0.68087308]


In [ ]:
def loss_func(x, t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/(len(x))

In [ ]:
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]
        
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x) # f(x+delta_x)

        x[idx]=float(tmp_val)-delta_x
        fx2=f(x) # f(x-delta_x)

        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()
    return grad

In [ ]:
def predict(x):
    y=np.dot(x, w)+b
    return y

In [ ]:
learning_rate=1e-6

f=lambda x: loss_func(x_data, t_data)

print("Initial error value=", loss_func(x_data, t_data), "Initial w=", w, "b=",b)

for step in range(20001):
    w-=learning_rate*numerical_derivative(f, w)
    b-=learning_rate*numerical_derivative(f, b)

    if step % 400==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), "w=", w, "b=",b)

Initial error value= 101.95878606749204 Initial w= [[0.94531651]
 [0.81143993]
 [0.1711562 ]] b= [0.68087308]
step= 0 error value= 96.52129901940236 w= [[0.94664424]
 [0.81276857]
 [0.17257686]] b= [0.68088914]
step= 400 error value= 30.770751994491828 w= [[0.97246526]
 [0.83784003]
 [0.22075076]] b= [0.68131826]
step= 800 error value= 30.00281029723963 w= [[0.96555462]
 [0.83018535]
 [0.23492197]] b= [0.68135642]
step= 1200 error value= 29.260062314557718 w= [[0.95872466]
 [0.82268975]
 [0.24885985]] b= [0.68139271]
step= 1600 error value= 28.541660247968963 w= [[0.95197436]
 [0.81535018]
 [0.26256835]] b= [0.68142717]
step= 2000 error value= 27.84678528185754 w= [[0.94530274]
 [0.80816365]
 [0.27605136]] b= [0.68145983]
step= 2400 error value= 27.17464658323027 w= [[0.93870881]
 [0.80112722]
 [0.28931267]] b= [0.68149071]
step= 2800 error value= 26.52448033619052 w= [[0.93219161]
 [0.79423801]
 [0.30235605]] b= [0.68151985]
step= 3200 error value= 25.89554880991628 w= [[0.92575017]
 

In [ ]:
print(predict(np.array([[75,80,85]])))
print(predict(np.array([[85,80,75]])))
print(predict(np.array([[75,85,80]])))


[[162.03573794]]
[[162.15172779]]
[[161.54969509]]
