In [1]:
import numpy as np

In [2]:
def func1(x):
    return x**2

In [3]:
print(func1(3))

9


2*x**2+3*x+1

In [4]:
def func2(x):
    return 2*x**2+3*x+1

In [5]:
print(func2(2))

15


In [6]:
def numerical_derivative(f, x):
    delta_x=1e-4
    return (f(x+delta_x)-f(x-delta_x))/(2*delta_x)

In [7]:
result=numerical_derivative(func1, 3)
print(result)

6.000000000012662


In [8]:
result2=numerical_derivative(func2, 2)
result2

11.00000000000989

# 벡터(배열) 입력 가능 확장

In [9]:
import numpy as np

def numerical_derivative(f, x):
    x = np.array(x, dtype=float)  # 리스트나 스칼라도 배열로 변환
    delta_x = 1e-4
    
    return (f(x + delta_x) - f(x - delta_x)) / (2 * delta_x)

# 스칼라 입력

In [10]:
print(numerical_derivative(func1, 3.0))  
# 결과: 6.000000000012662 (실제값 6.0에 근사)

6.000000000012662


# 벡터 입력

In [11]:
xs = [1.0, 2.0, 3.0, 4.0]
print(numerical_derivative(func1, xs))
# 결과: [2. 4. 6. 8.] (각 x에 대한 도함수 값)

[2. 4. 6. 8.]


In [12]:
import numpy as np

def numerical_partial_derivative(f, x):
    """
    f : 다변수 함수, 입력은 1차원 numpy 배열
    x : 미분을 구할 점 (리스트나 배열)
    반환값: 각 변수에 대한 편미분 값이 담긴 1차원 numpy 배열
    """
    x = np.array(x, dtype=float)
    delta_x = 1e-4
    grad = np.zeros_like(x)

    for i in range(len(x)):
        x1 = np.copy(x)
        x2 = np.copy(x)
        
        x1[i] += delta_x
        x2[i] -= delta_x
        
        grad[i] = (f(x1) - f(x2)) / (2 * delta_x)

    return grad

# 아래부터는 어려운 내용이니 참고만 하고, 나중에 다시 학습

# 2변수 함수

In [13]:
# 예: f(x, y) = x^2 + y^3
def func(v):
    x, y = v
    return x**2 + y**3

point = [3.0, 2.0]
print(numerical_partial_derivative(func, point))
# 결과: [6.0, 12.0]  (∂f/∂x=2x=6, ∂f/∂y=3y^2=12)

[ 6.         12.00000001]


# 3변수 함수

In [14]:
# 예: f(x, y, z) = x*y + sin(z)
def func3(v):
    x, y, z = v
    return x*y + np.sin(z)

print(numerical_partial_derivative(func3, [1.0, 2.0, np.pi/4]))
# 결과: [2.0, 1.0, cos(pi/4)≈0.7071]

[2.         1.         0.70710678]


# 다변수 함수 + 여러 점 동시 계산

In [15]:
import numpy as np

def batch_numerical_partial_derivative(f, points):
    """
    f : 다변수 함수, 입력은 1차원 numpy 배열
    points : 여러 점의 좌표 (2D 배열-like), shape: (n_points, n_variables)
    반환값: 각 점마다의 그래디언트 벡터 (shape: (n_points, n_variables))
    """
    points = np.atleast_2d(points).astype(float)
    n_points, n_vars = points.shape
    delta_x = 1e-4
    grads = np.zeros((n_points, n_vars))

    for p_idx, point in enumerate(points):
        grad = np.zeros(n_vars)
        for i in range(n_vars):
            x1 = np.copy(point)
            x2 = np.copy(point)
            x1[i] += delta_x
            x2[i] -= delta_x
            grad[i] = (f(x1) - f(x2)) / (2 * delta_x)
        grads[p_idx] = grad

    return grads

# 2변수 함수

In [16]:
# f(x, y) = x^2 + y^3
def func(v):
    x, y = v
    return x**2 + y**3

points = [
    [3.0, 2.0],
    [1.0, -1.0],
    [0.0, 0.0]
]

print(batch_numerical_partial_derivative(func, points))
# 예상 결과:
# [
#   [6.0, 12.0],   # (x=3, y=2)
#   [2.0,  3.0],   # (x=1, y=-1)
#   [0.0,  0.0]    # (x=0, y=0)
# ]

[[6.00000000e+00 1.20000000e+01]
 [2.00000000e+00 3.00000001e+00]
 [0.00000000e+00 1.00000000e-08]]


# 3변수 함수

In [17]:
# f(x, y, z) = x*y + sin(z)
def func3(v):
    x, y, z = v
    return x*y + np.sin(z)

print(batch_numerical_partial_derivative(func3, [[1.0, 2.0, np.pi/4],
                                                 [0.0, 1.0, np.pi/2]]))
# 결과:
# [
#   [ 2.0,  1.0,  cos(pi/4) ≈ 0.7071 ],
#   [ 1.0,  0.0,  cos(pi/2)  = 0.0   ]
# ]

[[2.         1.         0.70710678]
 [1.         0.         0.        ]]


- 여러 점에서 동시에 편미분(그래디언트) 계산 가능
- 점의 개수 n과 변수 개수 m에 대해 O(n * m) 계산
- 중앙 차분법이라 정확도와 안정성 우수

# 다변수 입력 → 다변수 출력 함수의 야코비안(Jacobian) 행렬을 계산

In [18]:
import numpy as np

def numerical_jacobian(F, x):
    """
    F : 다변수 입력 → 다변수 출력 함수
        입력: shape (n_vars,) numpy 배열
        출력: shape (n_outputs,) numpy 배열
    x : 미분을 구할 점 (1D array-like)    
    반환값: 야코비안 행렬 shape (n_outputs, n_vars)
    """
    x = np.array(x, dtype=float)
    delta_x = 1e-4

    y0 = np.atleast_1d(F(x))
    n_outputs = y0.size
    n_vars = x.size
    
    J = np.zeros((n_outputs, n_vars))    
    for i in range(n_vars):
        x1 = np.copy(x)
        x2 = np.copy(x)
        x1[i] += delta_x
        x2[i] -= delta_x
        
        f1 = np.atleast_1d(F(x1))
        f2 = np.atleast_1d(F(x2))
        
        J[:, i] = (f1 - f2) / (2 * delta_x)
    
    return J

 # 2변수 입력, 2변수 출력

In [19]:
# 예: F(x, y) = [x^2 + y, sin(x) * y]
def F(v):
    x, y = v
    return np.array([
        x**2 + y,
        np.sin(x) * y
    ])

point = [1.0, 2.0]
J = numerical_jacobian(F, point)
print(J)

#(각 열이 각각 ∂F/∂x, ∂F/∂y)

[[2.         1.        ]
 [1.08060461 0.84147098]]


# 3변수 입력, 2변수 출력

In [20]:
# F(x, y, z) = [x*y + z, e^x + cos(y) + z^2]
def F2(v):
    x, y, z = v
    return np.array([
        x*y + z,
        np.exp(x) + np.cos(y) + z**2
    ])

point = [1.0, 0.0, 2.0]
print(numerical_jacobian(F2, point))

[[0.         1.         1.        ]
 [2.71828183 0.         4.        ]]


- 다변수 벡터 함수의 야코비안 행렬 계산 가능
- 각 열(column)이 입력 변수에 대한 편미분 벡터
- 중앙 차분법 사용 → 정확도 O(h²)
- F는 반드시 Numpy 배열 연산 지원해야 함

# 여러 점(batch)에 대해 한꺼번에 야코비안(Jacobian) 계산

In [21]:
import numpy as np

def batch_numerical_jacobian(F, points):
    """
    F : R^n → R^m 형태의 벡터 함수
        입력: shape (n_vars,) numpy 배열
        출력: shape (n_outputs,) numpy 배열
    points : 여러 점의 좌표 (shape: (n_points, n_vars))    
    반환값: shape (n_points, n_outputs, n_vars)
            각 점에 대한 야코비안 행렬
    """
    points = np.atleast_2d(points).astype(float)
    n_points, n_vars = points.shape
    delta_x = 1e-4

    # 첫 번째 점에서 출력 차원 확인
    example_y = np.atleast_1d(F(points[0]))
    n_outputs = example_y.size

    # 결과 초기화
    J_all = np.zeros((n_points, n_outputs, n_vars))

    for p_idx, point in enumerate(points):
        J = np.zeros((n_outputs, n_vars))
        for i in range(n_vars):
            x1 = np.copy(point)
            x2 = np.copy(point)
            x1[i] += delta_x
            x2[i] -= delta_x

            f1 = np.atleast_1d(F(x1))
            f2 = np.atleast_1d(F(x2))
            J[:, i] = (f1 - f2) / (2 * delta_x)

        J_all[p_idx] = J

    return J_all

# 2변수 입력 → 2변수 출력

In [22]:
# F(x, y) = [x^2 + y, sin(x) * y]
def F(v):
    x, y = v
    return np.array([
        x**2 + y,
        np.sin(x) * y
    ])

points = [
    [1.0, 2.0],
    [0.0, 1.0],
    [2.0, -1.0]
]

J_batch = batch_numerical_jacobian(F, points)
print(J_batch)
# shape: (3, 2, 2) → (n_points, n_outputs, n_vars)

[[[2.         1.        ]
  [1.08060461 0.84147098]]

 [[0.         1.        ]
  [1.         0.        ]]

 [[4.         1.        ]
  [0.41614684 0.90929743]]]


# 3변수 입력 → 2변수 출력

In [23]:
# F(x, y, z) = [x*y + z, e^x + cos(y) + z^2]
def F2(v):
    x, y, z = v
    return np.array([
        x*y + z,
        np.exp(x) + np.cos(y) + z**2
    ])

points = [[1.0, 0.0, 2.0],
          [0.5, 1.0, -1.0]]

print(batch_numerical_jacobian(F2, points))

[[[ 0.          1.          1.        ]
  [ 2.71828183  0.          4.        ]]

 [[ 1.          0.5         1.        ]
  [ 1.64872127 -0.84147098 -2.        ]]]


- 여러 점에서 동시에 야코비안 계산 가능 (shape: (n_points, m, n))
- 중앙 차분법 사용 → 높은 정확도
- F는 반드시 Numpy 배열 연산 지원
- 대량 데이터 처리 시, for문 대신 병렬화(parellelization) 적용 가능

# 벡터화 + 병렬 최적화
NumPy 브로드캐스팅으로 불필요한 파이썬 루프 제거, 멀티코어 병렬 계산이 가능, 

In [24]:
import numpy as np
from joblib import Parallel, delayed

def batch_numerical_jacobian_fast(F, points, n_jobs=-1):
    """
    병렬 + 브로드캐스팅 최적화 Jacobian 계산
    F : R^n → R^m 함수
    points : shape (n_points, n_vars)
    n_jobs : 병렬 실행에 사용할 코어 수 (-1: 모든 CPU 사용)
    """
    points = np.atleast_2d(points).astype(float)
    delta_x = 1e-4
    n_points, n_vars = points.shape

    # 첫 점에서 출력 차원 확인
    example_y = np.atleast_1d(F(points[0]))
    n_outputs = example_y.size

    def jacobian_at_point(point):
        # 브로드캐스팅을 이용해 한 번에 변형된 좌표 생성
        perturb = np.eye(n_vars) * delta_x
        plus_points = point + perturb
        minus_points = point - perturb

        f_plus = np.array([F(p) for p in plus_points])
        f_minus = np.array([F(m) for m in minus_points])

        return ((f_plus - f_minus) / (2 * delta_x)).T  # shape: (n_outputs, n_vars)

    # 병렬 실행
    results = Parallel(n_jobs=n_jobs)(delayed(jacobian_at_point)(pt) for pt in points)
    return np.array(results)  # shape: (n_points, n_outputs, n_vars)

In [25]:
# 예시 함수: F(x, y, z) = [x*y + z, e^x + cos(y) + z^2]
def F(v):
    x, y, z = v
    return np.array([
        x*y + z,
        np.exp(x) + np.cos(y) + z**2
    ])

points = [
    [1.0, 0.0, 2.0],
    [0.5, 1.0, -1.0],
    [2.0, -1.0, 0.5]
]

J_fast = batch_numerical_jacobian_fast(F, points)
print(J_fast.shape)  # (3, 2, 3)
print(J_fast)        # 각 점의 Jacobian 출력

(3, 2, 3)
[[[ 0.          1.          1.        ]
  [ 2.71828183  0.          4.        ]]

 [[ 1.          0.5         1.        ]
  [ 1.64872127 -0.84147098 -2.        ]]

 [[-1.          2.          1.        ]
  [ 7.38905611  0.84147098  1.        ]]]


-브로드캐스팅으로 Δx 적용 포인트를 한 번에 생성
-멀티코어 병렬 처리(joblib.Parallel)로 각 점 계산 병렬화
-CPU가 많을수록 큰 데이터셋에서 속도 향상이 큼
-순차 실행 대비 수십 배 빠를 수 있음 (특히 m, n이 큰 경우)

#  CuPy 활용, 수천~수만 개의 점에 대한 Jacobian 계산 속도 획기적 향상
# 엔비디아 GeForce 그래픽 카드 필요

In [ ]:
!pip install cupy

  Using cached cupy-14.0.1.tar.gz (3.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      Generating CUPY_CACHE_KEY from header files...
      CUPY_CACHE_KEY (2006 files matching C:\Users\it\AppData\Local\Temp\pip-install-vwqnfv0p\cupy_a5a4c5c204cf4635b71cdb55471e624c\cupy\_core\include\**): f0aff8b0140d99853e8aff1d8ba78166f39f3c73
      Looking for NVTX from: []
      NVTX could not be found
      
      -------- Configuring Module: cuda --------
      Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      **************************************************
      *** WARNING: Cannot check compute capability
      Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      **************************************************
    

In [27]:
import cupy as cp

def batch_numerical_jacobian_gpu(F, points, delta_x=1e-4):
    """
    GPU(CuPy) 기반 batch Jacobian 계산
    F : R^n → R^m 함수 (입/출력 모두 cupy.ndarray 지원)
    points : shape (n_points, n_vars) cupy/numpy 배열
    """
    points = cp.asarray(points, dtype=cp.float64)  # GPU 메모리로 이동
    n_points, n_vars = points.shape

    # 첫 점으로 출력 차원 확인
    example_y = cp.atleast_1d(F(points[0]))
    n_outputs = example_y.size

    # 결과 저장 배열 (GPU 메모리)
    J_all = cp.zeros((n_points, n_outputs, n_vars), dtype=cp.float64)

    # 각 점에 대해 Jacobian 계산 (GPU에서 반복)
    for p_idx in range(n_points):
        point = points[p_idx]
        perturb = cp.eye(n_vars) * delta_x

        plus_pts = point + perturb
        minus_pts = point - perturb

        f_plus = cp.stack([F(p) for p in plus_pts])
        f_minus = cp.stack([F(m) for m in minus_pts])

        J_all[p_idx] = ((f_plus - f_minus) / (2 * delta_x)).T

    return J_all

ModuleNotFoundError: No module named 'cupy'

In [ ]:
# CuPy 기반 연산이 가능한 함수
def F_gpu(v):
    x, y, z = v
    return cp.array([
        x * y + z,
        cp.exp(x) + cp.cos(y) + z**2
    ])

# 여러 점
points = [
    [1.0, 0.0, 2.0],
    [0.5, 1.0, -1.0],
    [2.0, -1.0, 0.5]
]

J_gpu = batch_numerical_jacobian_gpu(F_gpu, points)
print(J_gpu.get())  # GPU → CPU로 복사해 출력

-CUDA GPU 메모리에서 연산하므로 NumPy CPU 버전 대비 수십~수백 배 빠를 수 있음
-CuPy는 NumPy API와 거의 동일 → 코드 변경 최소화
-대규모 (n_points, n_vars) 데이터에서 성능 이점이 극대화됨
-NVIDIA GPU + CUDA 환경이 필요
-F 함수는 반드시 CuPy 연산을 사용해야 함 (cp.sin, cp.exp 등)
-너무 작은 delta_x 사용 시 부동소수점 오차 주의

# CPU/Numpy 버전과 GPU/CuPy 버전을 자동 전환하는 통합한 함수

In [ ]:
import numpy as np

try:
    import cupy as cp
    _cupy_available = True
except ImportError:
    _cupy_available = False

def batch_numerical_jacobian_auto(F_cpu, F_gpu=None, points=None, delta_x=1e-4):
    """
    CPU/Numpy ↔ GPU/CuPy 자동 선택 Jacobian 계산
    F_cpu : NumPy 기반 함수
    F_gpu : (선택) CuPy 기반 함수. None이면 CPU 버전을 GPU에서도 사용 불가
    points : (n_points, n_vars) 점 집합
    """
    if points is None:
        raise ValueError("points 인자를 반드시 지정해야 합니다.")
    
    # GPU 사용 가능 여부 판별
    use_gpu = _cupy_available and F_gpu is not None
    if use_gpu:
        xp = cp
        F = F_gpu
        points = xp.asarray(points, dtype=xp.float64)
    else:
        xp = np
        F = F_cpu
        points = xp.asarray(points, dtype=xp.float64)

    n_points, n_vars = points.shape
    example_y = xp.atleast_1d(F(points[0]))
    n_outputs = example_y.size

    J_all = xp.zeros((n_points, n_outputs, n_vars), dtype=xp.float64)

    for p_idx in range(n_points):
        point = points[p_idx]
        perturb = xp.eye(n_vars) * delta_x
        plus_pts = point + perturb
        minus_pts = point - perturb
        f_plus = xp.stack([F(p) for p in plus_pts])
        f_minus = xp.stack([F(m) for m in minus_pts])
        J_all[p_idx] = ((f_plus - f_minus) / (2 * delta_x)).T

    # GPU 사용 시 CPU 메모리로 변환
    if use_gpu:
        return J_all.get()
    else:
        return J_all

In [ ]:
# CPU 기반 함수
def F_cpu(v):
    x, y, z = v
    return np.array([
        x*y + z,
        np.exp(x) + np.cos(y) + z**2
    ])

# GPU(CuPy) 기반 함수
def F_gpu(v):
    x, y, z = v
    return cp.array([
        x*y + z,
        cp.exp(x) + cp.cos(y) + z**2
    ])

points = [
    [1.0, 0.0, 2.0],
    [0.5, 1.0, -1.0]
]

Jacobian = batch_numerical_jacobian_auto(F_cpu, F_gpu, points)
print(Jacobian)

[[[ 0.          1.          1.        ]
  [ 2.71828183  0.          4.        ]]

 [[ 1.          0.5         1.        ]
  [ 1.64872127 -0.84147098 -2.        ]]]


- GPU 사용 가능 & CUDA 함수 제공 시 → CuPy 사용
- GPU 불가능 or GPU 함수 미제공 시 → NumPy CPU 버전 사용
- 공통 코드이므로 유지보수가 간편
- 필요 시 delta_x 조정 가능

# CPU ↔ GPU 자동 전환 + CPU 병렬

In [ ]:
import numpy as np
from joblib import Parallel, delayed

try:
    import cupy as cp
    _cupy_available = True
except ImportError:
    _cupy_available = False

def batch_numerical_jacobian_final(F_cpu, F_gpu=None, points=None, delta_x=1e-4, n_jobs=-1):
    """
    CPU/GPU 자동 전환 + CPU 병렬 처리 Jacobian 계산
    ------------------------------------------------
    F_cpu : NumPy 기반 함수
    F_gpu : (선택) CuPy 기반 함수
    points : (n_points, n_vars) 점 집합
    delta_x : 중앙차분법 간격
    n_jobs : CPU 병렬 처리 코어 수 (-1: 모든 CPU 사용)
    """
    if points is None:
        raise ValueError("points 인자를 반드시 지정해야 합니다.")

    # GPU 사용 여부 결정
    use_gpu = _cupy_available and F_gpu is not None
    if use_gpu:
        xp = cp
        F = F_gpu
        points = xp.asarray(points, dtype=xp.float64)
    else:
        xp = np
        F = F_cpu
        points = xp.asarray(points, dtype=xp.float64)

    n_points, n_vars = points.shape
    example_y = xp.atleast_1d(F(points[0]))
    n_outputs = example_y.size

    def jacobian_at_point(point):
        perturb = xp.eye(n_vars) * delta_x
        plus_pts = point + perturb
        minus_pts = point - perturb
        f_plus = xp.stack([F(p) for p in plus_pts])
        f_minus = xp.stack([F(m) for m in minus_pts])
        return ((f_plus - f_minus) / (2 * delta_x)).T

    if use_gpu:
        # GPU에서는 전체 반복을 GPU 메모리 상에서 순차 계산(병렬 필요 X)
        J_all = xp.zeros((n_points, n_outputs, n_vars), dtype=xp.float64)
        for p_idx in range(n_points):
            J_all[p_idx] = jacobian_at_point(points[p_idx])
        return J_all.get()

    else:
        # CPU에서는 Joblib로 병렬 처리
        results = Parallel(n_jobs=n_jobs)(
            delayed(jacobian_at_point)(pt) for pt in points
        )
        return np.array(results)

In [ ]:
# CPU 버전 함수
def F_cpu(v):
    x, y, z = v
    return np.array([
        x*y + z,
        np.exp(x) + np.cos(y) + z**2
    ])

# GPU 버전 함수 (선택)
def F_gpu(v):
    x, y, z = v
    return cp.array([
        x*y + z,
        cp.exp(x) + cp.cos(y) + z**2
    ])

points = [
    [1.0, 0.0, 2.0],
    [0.5, 1.0, -1.0],
    [2.0, -1.0, 0.5]
]

J_final = batch_numerical_jacobian_final(F_cpu, F_gpu, points)
print(J_final.shape)  # (3, 2, 3)
print(J_final)

(3, 2, 3)
[[[ 0.          1.          1.        ]
  [ 2.71828183  0.          4.        ]]

 [[ 1.          0.5         1.        ]
  [ 1.64872127 -0.84147098 -2.        ]]

 [[-1.          2.          1.        ]
  [ 7.38905611  0.84147098  1.        ]]]


GPU 가능 + GPU 함수 제공 → CuPy GPU 연산

GPU 불가능 or GPU 함수 미제공 → NumPy + Joblib 병렬 CPU 연산

중앙 차분법 사용으로 정확도 높음 (O(h²))

n_jobs로 CPU 병렬 처리 스레드 수 지정 가능 (-1이면 모든 CPU 코어 사용)

# CPU/GPU 자동 전환 + 병렬 처리 + 브로드캐스팅 최적화

In [ ]:
import numpy as np
from joblib import Parallel, delayed

try:
    import cupy as cp
    _cupy_available = True
except ImportError:
    _cupy_available = False

def batch_numerical_jacobian_ultimate(F_cpu, F_gpu=None, points=None, delta_x=1e-4, n_jobs=-1):
    """
    궁극의 Jacobian 계산기
    ------------------------------------------------
    - GPU 가능 시 CuPy 사용
    - GPU 불가 시 NumPy + Joblib 병렬 처리
    - 브로드캐스팅 사용으로 불필요한 반복 최소화
    ------------------------------------------------
    F_cpu : NumPy 기반 함수
    F_gpu : (선택) CuPy 기반 함수
    points : (n_points, n_vars) 점 집합
    delta_x : 중앙차분법 Δx
    n_jobs : CPU 병렬 처리 코어 수 (-1: 모든 CPU 사용)
    """
    if points is None:
        raise ValueError("points 인자를 반드시 지정해야 합니다.")
    
    # GPU 사용 여부 판단
    use_gpu = _cupy_available and (F_gpu is not None)
    xp = cp if use_gpu else np
    F = F_gpu if use_gpu else F_cpu
    points = xp.asarray(points, dtype=xp.float64)

    n_points, n_vars = points.shape
    example_y = xp.atleast_1d(F(points[0]))
    n_outputs = example_y.size

    def jacobian_at_point(point):
        # 브로드캐스팅으로 +Δx / -Δx 포인트 생성
        identity = xp.eye(n_vars) * delta_x
        plus_pts = point + identity
        minus_pts = point - identity

        # 한 번에 계산 (m×n 행렬)
        f_plus = xp.stack([F(p) for p in plus_pts], axis=0)
        f_minus = xp.stack([F(m) for m in minus_pts], axis=0)
        return ((f_plus - f_minus) / (2 * delta_x)).T

    if use_gpu:
        # GPU에서는 순차 루프가 커널 실행 부담이 적어서 효율적
        J_all = xp.stack([jacobian_at_point(pt) for pt in points], axis=0)
        return J_all.get()  # CPU 메모리로 복사
    else:
        # CPU 병렬 처리
        results = Parallel(n_jobs=n_jobs)(
            delayed(jacobian_at_point)(pt) for pt in points
        )
        return np.array(results)

In [ ]:
# CPU 기반 함수
def F_cpu(v):
    x, y, z = v
    return np.array([
        x*y + z,
        np.exp(x) + np.cos(y) + z**2
    ])

# GPU 기반 함수 (선택)
def F_gpu(v):
    x, y, z = v
    return cp.array([
        x*y + z,
        cp.exp(x) + cp.cos(y) + z**2
    ])

points = [
    [1.0, 0.0, 2.0],
    [0.5, 1.0, -1.0],
    [2.0, -1.0, 0.5]
]

J = batch_numerical_jacobian_ultimate(F_cpu, F_gpu, points)
print(J.shape)  # (3, 2, 3)
print(J)

(3, 2, 3)
[[[ 0.          1.          1.        ]
  [ 2.71828183  0.          4.        ]]

 [[ 1.          0.5         1.        ]
  [ 1.64872127 -0.84147098 -2.        ]]

 [[-1.          2.          1.        ]
  [ 7.38905611  0.84147098  1.        ]]]


GPU, CPU 모두에서 수천~수만 개의 점에 대해 최고 속도로 Jacobian을 계산

# 성능 최적화 방법
- GPU일 때 → CuPy 내부 벡터 연산 + 브로드캐스팅으로 속도 향상
- CPU일 때 → Joblib 병렬 처리로 다중 코어 활용
- 브로드캐스팅으로 Δx 적용 시 불필요한 for 루프 제거 → Python 오버헤드 감소
- 중앙 차분법 사용해 O(h²) 정확도 유지

In [ ]:
def numerical_derivative2(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)
    print('x:',x)
    print('grad:',grad)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    # flags : c_index(1차원 array일때), multi_index(2차원 이상일 때)
    # op_flags : 읽기/쓰기 옵션설정,default :readonly

    while not it.finished:
        idx=it.multi_index
        print('idx:',idx, 'x[idx]:',x[idx])
        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx]=(fx1-fx2)/(2*delta_x)
        print('grad[idx]:', grad[idx])
        print('grad:', grad)

        x[idx]=tmp_val
        it.iternext()

    return grad

In [ ]:
def func3(input):
    x=input[0]
    y=input[1]
    return (2*x + 3*x*y + np.power(y, 3))

In [ ]:
numerical_derivative2(func3, np.array([1.0, 2.0]))

x: [1. 2.]
grad: [0. 0.]
idx: (0,) x[idx]: 1.0
grad[idx]: 7.999999999990237
grad: [8. 0.]
idx: (1,) x[idx]: 2.0
grad[idx]: 15.000000010019221
grad: [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [ ]:
numerical_derivative2(func3, np.array([2.0, 1.0]))

x: [2. 1.]
grad: [0. 0.]
idx: (0,) x[idx]: 2.0
grad[idx]: 5.0000000000149925
grad: [5. 0.]
idx: (1,) x[idx]: 1.0
grad[idx]: 9.00000001000656
grad: [5.         9.00000001]


array([5.        , 9.00000001])

In [ ]:
numerical_derivative2(func1, np.array([3.0]))

x: [3.]
grad: [0.]
idx: (0,) x[idx]: 3.0
grad[idx]: 6.000000000012662
grad: [6.]


array([6.])

In [ ]:
arr1=np.array([[1.0,2.0],[3.0,4.0]])
arr1

array([[1., 2.],
       [3., 4.]])

In [ ]:
def func4(input):
    w=input[0][0]
    x=input[0][1]
    y=input[1][0]
    z=input[1][1]

    return (w*x + w*y*z + 3*w + z*np.power(y,2))

In [ ]:
numerical_derivative2(func4, arr1)

x: [[1. 2.]
 [3. 4.]]
grad: [[0. 0.]
 [0. 0.]]
idx: (0, 0) x[idx]: 1.0
grad[idx]: 16.999999999995907
grad: [[17.  0.]
 [ 0.  0.]]
idx: (0, 1) x[idx]: 2.0
grad[idx]: 1.0000000000331966
grad: [[17.  1.]
 [ 0.  0.]]
idx: (1, 0) x[idx]: 3.0
grad[idx]: 28.000000000041325
grad: [[17.  1.]
 [28.  0.]]
idx: (1, 1) x[idx]: 4.0
grad[idx]: 12.00000000000756
grad: [[17.  1.]
 [28. 12.]]


array([[17.,  1.],
       [28., 12.]])