In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x_data1=np.array([1,2,3,4,5]).reshape(5,1)
t_data1=np.array([3,5,7,9,11]).reshape(5,1)
print(x_data1)
print(t_data1)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [3]:
x_data2=np.array([9,14,21,27,32,37]).reshape(6,1)
t_data2=np.array([74,81,86,90,88,92]).reshape(6,1)

In [4]:
w=np.random.rand(1,1)
b=np.random.rand(1)
print(w, b)

[[0.52571665]] [0.42429633]


In [5]:
def loss_func1(x, t):
    y=np.dot(x, w)+ b

    return (np.sum((t-y)**2))/(len(x))

In [6]:
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()

    return grad

In [7]:
def predict(x):
    y=np.dot(x,w)+b
    return y

In [8]:
cost_list=[]
learning_rate=1e-4

f=lambda x: loss_func1(x_data2, t_data2)

print("오차값:", loss_func1(x_data2, t_data2), '초기값 가중치(w)=',w, '초기값 편향(b)=',b )

for step in range(200001):
    w-=learning_rate*numerical_derivative(f, w)
    b-=learning_rate*numerical_derivative(f, b)

    if step % 100==0:
        print('반복횟수:', step, '오차값:',loss_func1(x_data2, t_data2), 'w:',w, 'b:',b)


오차값: 5257.638491125274 초기값 가중치(w)= [[0.52571665]] 초기값 편향(b)= [0.42429633]
반복횟수: 0 오차값: 4178.650451819167 w: [[0.8649782]] b: [0.43720824]
반복횟수: 100 오차값: 755.2817921591013 w: [[3.16592813]] b: [0.72242727]
반복횟수: 200 오차값: 750.8172165413116 w: [[3.15822982]] b: [0.93360186]
반복횟수: 300 오차값: 746.3791943549026 w: [[3.15055189]] b: [1.14414745]
반복횟수: 400 오차값: 741.9675679166385 w: [[3.14289683]] b: [1.35406598]
반복횟수: 500 오차값: 737.5821802341698 w: [[3.13526456]] b: [1.56335932]
반복횟수: 600 오차값: 733.2228752488877 w: [[3.12765503]] b: [1.77202933]
반복횟수: 700 오차값: 728.8894978303401 w: [[3.12006816]] b: [1.98007786]
반복횟수: 800 오차값: 724.5818937707835 w: [[3.11250388]] b: [2.18750678]
반복횟수: 900 오차값: 720.2999097796146 w: [[3.10496214]] b: [2.39431792]
반복횟수: 1000 오차값: 716.0433934779045 w: [[3.09744285]] b: [2.60051312]
반복횟수: 1100 오차값: 711.8121933930914 w: [[3.08994596]] b: [2.80609423]
반복횟수: 1200 오차값: 707.6061589535012 w: [[3.0824714]] b: [3.01106305]
반복횟수: 1300 오차값: 703.4251404829561 w: [[3.07501909]] b: [

In [9]:
predict(np.array([48]).reshape(1,1))

array([[99.61601101]])